-- DEPRECATED / NOT LOADED. The canonical schema now lives in `schema.ts`
-- (inlined as a string) so it is bundled by `tsc` and present at runtime in
-- production (`node dist`). Editing this file has NO effect — edit schema.ts.
